import Navbar from '@/app/components/Navbar'
import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import 'react-loading-skeleton/dist/skeleton.css'

import { Theme } from '@radix-ui/themes'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
// console.log(inter.variable)
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body className={inter.variable}>
    <Theme appearance="light" accentColor="mint">
      <Navbar/>
      <main className={'p-5'}>
        {children}
      </main>
    </Theme>
    </body>
    </html>
  )
}
